title: "Kolay Yemek Tarifleri"
description: "Kolay yemek tarifleri veri tabanı: Besin değerleri ile pratik yemekler, nefis yemek çeşitleri ve denenmiş yemek tarifleri fikirleri için açık kaynak API"
theme: jekyll-theme-primer
lang: "tr"
locale: "tr-TR"
image: "https://yemekyarismasi.com/yemek-yarismasi.png"
logo: "https://yemekyarismasi.com/yemek-yarismasi.png"